# Generated by Django 5.0.6 on 2024-07-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_rename_user_myuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Otp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=200, null=True)),
                ("phone", models.CharField(max_length=11)),
                ("code", models.SmallIntegerField()),
            ],
        ),
    ]
