# Generated by Django 5.0.6 on 2024-09-07 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="descriptionl",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="address",
            name="email",
        ),
    ]
