# Generated by Django 4.2.14 on 2024-09-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_descriptionl_address_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='address',
            name='meli_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='address',
            name='membership_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='membership_date'),
        ),
    ]
