# Generated by Django 4.2.14 on 2024-09-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_address_email_address_meli_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='address',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, verbose_name='پلاک'),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(blank=True, max_length=50, verbose_name='استان'),
        ),
    ]
