# Generated by Django 4.2.14 on 2024-09-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_address_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='avatar',
            field=models.ImageField(upload_to='media'),
        ),
    ]
