# Generated by Django 4.2.14 on 2024-09-24 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_myuser_first_name_myuser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(max_length=500, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='address',
            name='membership_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ عضویت'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=100, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
