# Generated by Django 5.0.6 on 2024-08-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_product_title_en"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productfeature",
            name="feature",
        ),
        migrations.AddField(
            model_name="productfeature",
            name="key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="Feature",
        ),
    ]
