# Generated by Django 4.2.14 on 2024-09-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SpecialOffer',
            field=models.BooleanField(default=False, verbose_name='پیشنهاد ویژه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
