# Generated by Django 4.2.14 on 2024-09-12 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileUser', '0002_alter_addressuser_address_alter_addressuser_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddressUser',
        ),
    ]
